import csv
import numpy as np

def parse_note(note):
    '''
        Parse the notes I wrote in the "Note" field of Flowlab.
        Those notes basically contain parameters used for the measurements
        in the format "Parameter=value", one per line.

        Returns:
            - notes, but as a list of individual subnotes
            - list of parameters names
            - lsit of paramters values
    '''
    notes = note.split('<br>')
    names = [p.strip().split('=')[0] for p in notes]
    values = [p.strip().split('=')[1] for p in notes]

    return notes, names, values

def parse(filename):
    '''
        Parse .log files generated by Flowlab.

        Returns:
        - date of the test (for reference)
        - title of the test (for reference)
        - notes (containing parameters of the test, line by line)
        - labels (i.e., names) of the data generated by Flowlab
        - data: a matrix containing the measured values as columns
    '''
    with open(filename) as raw:
        # Skip first line '[Information]'
        next(raw)

        # Read date and title
        date = raw.readline()[10:].strip()
        title = raw.readline()[6:].strip()

        # Extract param in note
        notes, names, values = parse_note(raw.readline()[5:])
        param = (names, values)

        # Compute number of samples from T_acq and T_s
        T_acq = 60 * float(values[0])
        T_s = float(values[1])
        N = int(T_acq/T_s) + 1

        # Initialize raw data vector
        data = np.zeros((N, 2))

        # Skip blank line and '[Data]'
        next(raw)
        next(raw)
        labels = raw.readline().split('\t')

        for (i, line) in enumerate(csv.reader(raw, delimiter='\t')):
            data[i, :] = [float(l.replace(',', '.')) for l in line]

    return date, title, notes, labels, data

